Issue#2
dailymp/samples-for-react-testing-library-training pull request #6
Opened 2020-04-06 11:26 UTC by Dacalez

Prepare a redux architecture with components styled using less

2020-04-07 10:14 UTC, dailymp requested changes
Please fix all comments to continue the process

2020-04-07 10:14 UTC, dailymp commented on 00 Base/src/components/MessageForm/MessageForm.less
> +    }
Try to format the code properly

2020-04-07 10:14 UTC, dailymp commented on 00 Base/src/components/MessageForm/MessageForm.less
> +};
The complete file need format

2020-04-07 10:14 UTC, dailymp commented on 00 Base/src/components/MessageForm/MessageForm.less
> +        background-color: @borderColor;
Try to be more semantic, for example you define an ``` @borderColor``` and use the same variable in background color? Try to improve this

2020-04-07 10:14 UTC, dailymp commented on 00 Base/src/components/MessageForm/MessageForm.tsx
> +    newMessage: any
Avoid using any, it is like not typing

2020-04-07 10:14 UTC, dailymp commented on 00 Base/src/components/MessageForm/MessageForm.tsx
> +        this.handleSubmit = this.handleSubmit.bind(this);
If you use lambda functions you can avoid this 2 lines, can you improve this?

2020-04-07 10:14 UTC, dailymp commented on 00 Base/src/components/MessageForm/MessageForm.tsx
> +export default connect(null, mapDispatchToProps)(MessageForm)
Please refactor to avoid export default

2020-04-07 10:14 UTC, dailymp commented on 00 Base/src/components/MessageList/MessageList.less
> +            background-color: @headerColor;
This is not semantic

2020-04-07 10:14 UTC, dailymp commented on 00 Base/src/components/MessageList/MessageList.tsx
> +    messages: any[];
Type this properly

2020-04-07 10:14 UTC, dailymp commented on 00 Base/src/components/MessageList/MessageList.less
> +};
Format this file

2020-04-07 10:14 UTC, dailymp commented on 00 Base/src/components/MessageList/MessageList.tsx
> +class MessageList extends React.Component<MessageListProps> {
Can you refactor this to functional component due to lack of state

2020-04-07 10:14 UTC, dailymp commented on 00 Base/src/components/MessagesSection/MessagesSection.tsx
> +    messages: any[];
This is not typed well

2020-04-07 10:14 UTC, dailymp commented on 00 Base/src/components/MessagesSection/MessagesSection.tsx
> +    messages: any[];
Improve typings

2020-04-07 10:14 UTC, dailymp commented on 00 Base/src/components/MessagesSection/MessagesSection.tsx
> +export default connect(mapStateToProps, mapDispatchToProps)(MessagesSection)
Refactor to avoid export default

2020-04-07 10:14 UTC, dailymp commented on 00 Base/src/components/MessagesSection/MessagesSection.tsx
> +export default connect(mapStateToProps, mapDispatchToProps)(MessagesSection)
https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/

2020-04-07 10:14 UTC, dailymp commented on 00 Base/src/components/index.tsx
> +import MessageList from './MessageList/MessageList';
Are you trying tu use barrel pattern? This file doesn't need to be .tsx, just with .ts is enough

2020-04-07 10:14 UTC, dailymp commented on 00 Base/src/myApi/myApi.ts
> +export const getListOfMessages = (): Promise<Object[]> => {
You can declare an interface for type Messages and avoid to type as Object

2020-04-07 10:14 UTC, dailymp commented on 00 Base/src/myApi/myApi.ts
> +}
Delete this unused function

2020-04-07 10:14 UTC, dailymp commented on 00 Base/src/myApi/myApi.ts
> +
Please format properly the code is a little bit lack of format and with a lot of extra spaces

2020-04-07 10:14 UTC, dailymp commented on 00 Base/src/myApi/myApi.ts
> +const resolveMessages = (listOfMessages: Object[]) => {
Avoid type with Object

2020-04-07 10:14 UTC, dailymp commented on 00 Base/src/myApi/myBackEndApiEndpoint.ts
> +let messages = [
Why let and not const?

2020-04-07 10:14 UTC, dailymp commented on 00 Base/src/myApi/myBackEndApiEndpoint.ts
> +]
I would prefer if you use a database fake as this one: https://github.com/typicode/json-server, in order to see how you work with axios

2020-04-07 10:14 UTC, dailymp commented on 00 Base/src/redux/reducers/MessagesReducer.js
> +import { GET_ALL, ADD_MESSAGE } from '../actions/MessagesActions'
I can see you are not using typescript properly, please fix it

2020-04-07 10:14 UTC, dailymp commented on 00 Base/src/redux/reducers/MessagesReducer.js
> +          return item.id == index;
This is reallly necesary? I think there are cleaner ways to do this here

2020-04-07 10:14 UTC, dailymp commented on 00 Base/src/redux/reducers/MessagesReducer.js
> +export default  MessagesReducer
Avoid export default

2020-04-07 10:14 UTC, dailymp commented on 00 Base/src/redux/stores/MessageStore.js
> +export default Messagestore;
This is duplicated please fix it

2020-04-07 10:16 UTC, dailymp requested changes

2020-04-07 10:16 UTC, dailymp commented on 02 Testing hooks/src/app.tsx
> +import { MyFruits } from './myComponent/myFruits';
Are you using this?

2020-04-08 11:42 UTC, dailymp commented
> Prepare a redux architecture with components styled using less

 @Dacalez  The PR sould be from your branch to develop branch is the correct way of working

2020-04-08 12:30 UTC, Dacalez commented
I have upload the changes and changed the PR base as well

2020-04-09 11:34 UTC, dailymp commented
> I have upload the changes and changed the PR base as well

Good job, but still pending a loader missing. Thanks!

2020-04-09 16:38 UTC, Dacalez commented
Problem with loader fixed

2020-04-10 07:44 UTC, merged